<h2>Contact</h2>
<p>Nous serions ravis de vous lire</p>
<p>N’hésitez pas à nous contacter pour toute réservation ou demande spéciale.    Notre équipe vous répondra dans les plus brefs délais.    Notre établissement est privatisable pour vos événements professionnels ou privés, avec un menu sur mesure, élaboré selon vos recommendations.</p>
<div class="form">
    <form method="post" action="">
        <legend>Vos cordonnées</legend>
        <label for="Prenom">Votre Prénom</label><input type="text" name="" value="" id="Prenom" class="sans">
        <label for="Nom">Votre Nom</label><input type="text" name="" value="" id="Nom" class="sans">
        <label for="mail">Votre mail</label><input type="email" name="" value="" id="mail" class="sans">
        <textarea for="message">Message</textarea>
        <button type="submit">Enregistrer</button>
    </form>
</div>
