
<div class="bd-example">
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="<?=$router->getWwwPath()?>/upload/plats/restaurant1.jpg" class="d-block w-100" alt="slide 1">
                <div class="carousel-caption d-none d-md-block">
                    <h2>Get Colourful*</h2>
                    <h3>Nouvelle recettes de Primtemps</h3>
                    <a href="<?=$router->generatePath("resto_plat_showAll")?>" class="btn chevron btn-default hidden-print">Découvrir </a>
                    <p>* Mettez-vous à la couleur</p>
                </div>
            </div>

            <div class="carousel-item">
                <img src="<?=$router->getWwwPath()?>/upload/plats/resto2.jpg" class="d-block w-100" alt="slide 2">
                <div class="carousel-caption d-none d-md-block">
                    <h2>Nouvelle recettes de Primtemps</h2>
                    <a href="<?=$router->generatePath("resto_plat_showAll")?>" class="btn chevron btn-default hidden-print">Découvrir </a>
                    <p>* Mettez-vous à la couleur</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="<?=$router->getWwwPath()?>/upload/plats/resto3.jpg" class="d-block w-100" alt="slide3">
                <div class="carousel-caption d-none d-md-block">
                    <h2>Nouvelle recettes de Primtemps</h2>
                     <a href="<?=$router->generatePath("resto_plat_showAll")?>" class="btn chevron btn-default hidden-print">Découvrir </a>
                    <p>* Mettez-vous à la couleur</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>

        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>



